part of '../main.dart';

class _ResumoFuncionario extends StatelessWidget {
  const _ResumoFuncionario();
  Future<List<dynamic>> _lista(String rota) async { final r=await apiService.get(rota); return r.statusCode==200 ? jsonDecode(r.body) as List<dynamic> : const []; }
  @override Widget build(BuildContext context)=>FutureBuilder<List<List<dynamic>>>(future:Future.wait([_lista('/api/clientes'),_lista('/api/ordens-servico'),_lista('/api/pedidos-produto'),_lista('/api/salarios')]),builder:(_,s){final d=s.data??const [[],[],[],[]];final hoje=DateTime.now().toIso8601String().substring(0,10);final servicos=d[1].where((x)=>x['dataServico']==hoje).length;final pedidos=d[2].where((x)=>x['status']=='SOLICITADO').length;final salario=d[3].isEmpty?0:(d[3].first['salario'] as num);return Wrap(spacing:16,runSpacing:16,children:[_Indicador('Meus clientes','${d[0].length}',Icons.people_outline,const Color(0xFF1565C0)),_Indicador('Serviços hoje','$servicos',Icons.build_outlined,const Color(0xFFF4A261)),_Indicador('Pedidos em aberto','$pedidos',Icons.shopping_cart_outlined,const Color(0xFFE76F51)),_Indicador('Salário previsto',formatarMoeda(salario),Icons.payments_outlined,const Color(0xFF1976D2))]);});
}

class _ProximosServicosFuncionario extends StatelessWidget { const _ProximosServicosFuncionario(); @override Widget build(BuildContext context)=>FutureBuilder<http.Response>(future:apiService.get('/api/ordens-servico'),builder:(_,s){if(!s.hasData)return const Card(child:Padding(padding:EdgeInsets.all(20),child:Center(child:CircularProgressIndicator())));if(s.data!.statusCode!=200)return const Card(child:ListTile(title:Text('Nenhum serviço disponível.')));final itens=jsonDecode(s.data!.body) as List<dynamic>;if(itens.isEmpty)return const Card(child:ListTile(leading:Icon(Icons.pool_outlined),title:Text('Nenhum serviço nas piscinas vinculadas.')));return Card(child:ListView.separated(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:itens.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i){final o=itens[i] as Map<String,dynamic>;final p=o['piscina']??{};return ListTile(leading:const CircleAvatar(child:Icon(Icons.pool)),title:Text('${(o['cliente']??{})['nome']??''} — ${p['nome']??'Piscina'}'),subtitle:Text('${o['dataServico']} • ${o['descricao']}'));}));});}

class _FuncionariosPage extends StatefulWidget { const _FuncionariosPage(); @override State<_FuncionariosPage> createState()=>_FuncionariosPageState(); }
class _FuncionariosPageState extends State<_FuncionariosPage> {
 late Future<List<dynamic>> dados; @override void initState(){super.initState();dados=carregar();}
 Future<List<dynamic>> carregar() async {final r=await apiService.get('/api/funcionarios');if(r.statusCode!=200)throw Exception('Não foi possível carregar funcionários.');return jsonDecode(r.body);}
 Future<void> novo() async {final nome=TextEditingController(), login=TextEditingController(), senha=TextEditingController(), telefone=TextEditingController(), percentual=TextEditingController(text:'75'); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Novo colaborador'),content:SizedBox(width:440,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:nome,decoration:const InputDecoration(labelText:'Nome *')),TextField(controller:login,decoration:const InputDecoration(labelText:'Usuário de acesso *')),TextField(controller:senha,obscureText:true,decoration:const InputDecoration(labelText:'Senha *')),TextField(controller:telefone,decoration:const InputDecoration(labelText:'Telefone')),TextField(controller:percentual,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Percentual sobre recebimentos'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Cadastrar'))])); if(ok!=true)return; final r=await apiService.post('/api/funcionarios',body:{'nome':nome.text.trim(),'login':login.text.trim(),'senha':senha.text,'telefone':telefone.text.trim(),'percentualMensalidade':double.tryParse(percentual.text.replaceAll(',','.'))??75});if(!mounted)return;if(r.statusCode>=200&&r.statusCode<300){setState(()=>dados=carregar());ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Colaborador cadastrado. Agora vincule as piscinas a ele.')));}else{ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Não foi possível cadastrar (${r.statusCode}).')));}}
 @override Widget build(BuildContext c)=>_PaginaLista(titulo:'Colaboradores',subtitulo:'Cadastre os acessos e depois defina as piscinas de responsabilidade.',acao:'Novo colaborador',onAcao:novo,futuro:dados,item:(f){final u=f['usuario']??{};return ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(u['nome']??''),subtitle:Text('Usuário: ${u['login']??''} • ${f['telefone']??'sem telefone'}'),trailing:Text('${f['percentualMensalidade']??75}%'));});
}

class _PiscinasPage extends StatefulWidget {const _PiscinasPage({required this.gestor});final bool gestor;@override State<_PiscinasPage> createState()=>_PiscinasPageState();}
class _PiscinasPageState extends State<_PiscinasPage>{late Future<List<dynamic>> dados;@override void initState(){super.initState();dados=carregar();}Future<List<dynamic>> carregar()async{final r=await apiService.get('/api/piscinas');if(r.statusCode!=200)throw Exception('Não foi possível carregar piscinas.');return jsonDecode(r.body);}
 Future<void> novo() async {final clientes=await _lista('/api/clientes');final funcs=await _lista('/api/funcionarios');if(clientes.isEmpty||!mounted)return;int cliente=clientes.first['id'];int? responsavel=funcs.isEmpty?null:funcs.first['id'];final nome=TextEditingController(),endereco=TextEditingController(),tipo=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(ctx)=>StatefulBuilder(builder:(_,setL)=>AlertDialog(title:const Text('Nova piscina'),content:SizedBox(width:500,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<int>(initialValue:cliente,decoration:const InputDecoration(labelText:'Cliente *'),items:clientes.map<DropdownMenuItem<int>>((x)=>DropdownMenuItem(value:x['id'],child:Text(x['nome']))).toList(),onChanged:(x)=>setL(()=>cliente=x!)),TextField(controller:nome,decoration:const InputDecoration(labelText:'Nome ou identificação *')),TextField(controller:endereco,maxLines:2,decoration:const InputDecoration(labelText:'Endereço da piscina *')),TextField(controller:tipo,decoration:const InputDecoration(labelText:'Tipo')),DropdownButtonFormField<int>(initialValue:responsavel,decoration:const InputDecoration(labelText:'Colaborador responsável'),items:funcs.map<DropdownMenuItem<int>>((x)=>DropdownMenuItem(value:x['id'],child:Text((x['usuario']??{})['nome']??''))).toList(),onChanged:(x)=>setL(()=>responsavel=x))]))),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Cadastrar'))])));if(ok!=true)return;final r=await apiService.post('/api/piscinas',body:{'clienteId':cliente,'nome':nome.text.trim(),'endereco':endereco.text.trim(),'tipo':tipo.text.trim(),'responsavelId':responsavel,'observacoes':''});if(!mounted)return;if(r.statusCode>=200&&r.statusCode<300){setState(()=>dados=carregar());ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Piscina cadastrada.')));}else{ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Não foi possível salvar (${r.statusCode}).')));}}
 Future<List<dynamic>> _lista(String url)async{final r=await apiService.get(url);return r.statusCode==200?jsonDecode(r.body):[];}
 Future<void> excluir(Map<String,dynamic> p) async {final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Excluir piscina?'),content:Text('Excluir ${p['nome']}?'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Excluir'))]));if(ok==true){final r=await apiService.delete('/api/piscinas/${p['id']}');if(r.statusCode>=200&&r.statusCode<300)setState(()=>dados=carregar());}}
 Future<void> editar(Map<String,dynamic> p) async {final nome=TextEditingController(text:p['nome']??''),endereco=TextEditingController(text:p['endereco']??''),tipo=TextEditingController(text:p['tipo']??'');final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Editar piscina'),content:SizedBox(width:440,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:nome,decoration:const InputDecoration(labelText:'Nome')),TextField(controller:endereco,decoration:const InputDecoration(labelText:'Endereço')),TextField(controller:tipo,decoration:const InputDecoration(labelText:'Tipo'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Salvar'))]));if(ok==true){final r=await apiService.put('/api/piscinas/${p['id']}',body:{'clienteId':(p['cliente']??{})['id'],'responsavelId':(p['responsavel']??{})['id'],'nome':nome.text.trim(),'endereco':endereco.text.trim(),'tipo':tipo.text.trim(),'volumeLitros':p['volumeLitros'],'observacoes':p['observacoes']??''});if(r.statusCode>=200&&r.statusCode<300)setState(()=>dados=carregar());}}
  @override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(28),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Piscinas',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),Text(widget.gestor?'Cada piscina tem endereço, cliente e responsável.':'Somente suas piscinas de responsabilidade.')])),if(widget.gestor)FilledButton.icon(onPressed:novo,icon:const Icon(Icons.add),label:const Text('Nova piscina'))]),const SizedBox(height:18),TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),labelText:'Pesquisar piscina, cliente ou endereço',border:OutlineInputBorder()),onChanged:(_)=>setState((){})),const SizedBox(height:12),Expanded(child:FutureBuilder<List<dynamic>>(future:dados,builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('${s.error}'));if(s.data!.isEmpty)return const Center(child:Text('Nenhuma piscina cadastrada.'));return Card(child:ListView.separated(itemCount:s.data!.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i){final p=s.data![i] as Map<String,dynamic>;final cl=p['cliente']??{},resp=p['responsavel']??{},u=resp['usuario']??{};return ListTile(leading:const CircleAvatar(child:Icon(Icons.pool)),title:Text(p['nome']??''),subtitle:Text('${cl['nome']??''} • ${p['endereco']??'endereço não informado'}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text(u['nome']??'Sem responsável'),if(widget.gestor)IconButton(icon:const Icon(Icons.edit_outlined),onPressed:()=>editar(p)),if(widget.gestor)IconButton(icon:const Icon(Icons.delete_outline,color:Colors.red),onPressed:()=>excluir(p))]));}));}))]));}

class _CobrancasPage extends StatefulWidget{const _CobrancasPage();@override State<_CobrancasPage> createState()=>_CobrancasPageState();}
class _CobrancasPageState extends State<_CobrancasPage>{late Future<List<dynamic>> dados;@override void initState(){super.initState();dados=carregar();}Future<List<dynamic>> carregar()async{final r=await apiService.get('/api/cobrancas');if(r.statusCode!=200)throw Exception('Não foi possível carregar cobranças.');return jsonDecode(r.body);}Future<void> pagar(Map<String,dynamic> x)async{final pago=x['status']=='PAGO';final r=await apiService.put(pago?'/api/cobrancas/${x['id']}/reabrir':'/api/cobrancas/${x['id']}/baixar?valor=${x['total']}');if(r.statusCode>=200&&r.statusCode<300)setState(()=>dados=carregar());}
 @override Widget build(BuildContext c)=>_PaginaLista(titulo:'Cobranças',subtitulo:'Mensalidades e valores de produtos e serviços.',futuro:dados,item:(x){final pago=x['status']=='PAGO';return ListTile(leading:Icon(pago?Icons.check_circle:Icons.pending_actions,color:pago?Colors.green:Colors.orange),title:Text((x['cliente']??{})['nome']??''),subtitle:Text('Vencimento: ${x['vencimento']} • ${x['status']}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text(formatarMoeda(x['total'] as num)),Switch(value:pago,onChanged:(_)=>pagar(x))]));});}

class _SalariosPage extends StatefulWidget{const _SalariosPage({required this.gestor});final bool gestor;@override State<_SalariosPage> createState()=>_SalariosPageState();}
class _SalariosPageState extends State<_SalariosPage>{late Future<List<dynamic>> dados;@override void initState(){super.initState();dados=carregar();}Future<List<dynamic>> carregar()async{final r=await apiService.get('/api/salarios');if(r.statusCode!=200)throw Exception('Não foi possível carregar salários.');return jsonDecode(r.body);}@override Widget build(BuildContext c){if(widget.gestor)return _PaginaLista(titulo:'Salários',subtitulo:'Cálculo sobre cobranças pagas dos clientes das piscinas vinculadas.',futuro:dados,item:(x){final f=x['funcionario']??{},u=f['usuario']??{};return ListTile(leading:const CircleAvatar(child:Icon(Icons.payments)),title:Text(u['nome']??''),subtitle:Text('${x['piscinas']} piscina(s) • ${x['clientes']} cliente(s)'),trailing:Text(formatarMoeda(x['salario'] as num),style:const TextStyle(fontWeight:FontWeight.bold)));});return Padding(padding:const EdgeInsets.all(28),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Meu salário',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('Resumo das piscinas sob sua responsabilidade.'),const SizedBox(height:24),FutureBuilder<List<dynamic>>(future:dados,builder:(_,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final x=s.data!.isEmpty?null:s.data!.first;if(x==null)return const Text('Nenhum vínculo encontrado.');return Wrap(spacing:16,runSpacing:16,children:[_Indicador('Total de clientes','${x['clientes']}',Icons.people_outline,const Color(0xFF1565C0)),_Indicador('Salário total',formatarMoeda(x['salario'] as num),Icons.payments_outlined,const Color(0xFF1976D2))]);})]));}}

class _PaginaLista extends StatelessWidget{const _PaginaLista({required this.titulo,required this.subtitulo,required this.futuro,required this.item,this.acao,this.onAcao});final String titulo,subtitulo;final Future<List<dynamic>> futuro;final Widget Function(Map<String,dynamic>) item;final String? acao;final VoidCallback? onAcao;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(28),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(titulo,style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),Text(subtitulo)])),if(acao!=null)FilledButton.icon(onPressed:onAcao,icon:const Icon(Icons.add),label:Text(acao!))]),const SizedBox(height:20),Expanded(child:FutureBuilder<List<dynamic>>(future:futuro,builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('${s.error}'));if(s.data!.isEmpty)return const Center(child:Text('Nenhum registro encontrado.'));return Card(child:ListView.separated(itemCount:s.data!.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i)=>item(s.data![i] as Map<String,dynamic>)));}))]));}



