spring.application.name=admin-pool-api
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/Admin_Poll
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never
