package br.com.adminpool.model;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.LocalDate;
@Entity @Table(name="cobrancas_mensais")
public class CobrancaMensal {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @ManyToOne(optional=false) private Cliente cliente; @Column(nullable=false) private String referencia; @Column(nullable=false) private LocalDate vencimento;
 @Column(nullable=false,precision=12,scale=2) private BigDecimal mensalidade; @Column(nullable=false,precision=12,scale=2) private BigDecimal produtos=BigDecimal.ZERO; @Column(nullable=false,precision=12,scale=2) private BigDecimal servicos=BigDecimal.ZERO; @Column(nullable=false,precision=12,scale=2) private BigDecimal total;
 @Enumerated(EnumType.STRING) private StatusCobranca status=StatusCobranca.PENDENTE; private LocalDate dataPagamento; private BigDecimal valorPago;
 public Long getId(){return id;} public void setId(Long v){id=v;} public Cliente getCliente(){return cliente;} public void setCliente(Cliente v){cliente=v;} public String getReferencia(){return referencia;} public void setReferencia(String v){referencia=v;} public LocalDate getVencimento(){return vencimento;} public void setVencimento(LocalDate v){vencimento=v;} public BigDecimal getMensalidade(){return mensalidade;} public void setMensalidade(BigDecimal v){mensalidade=v;} public BigDecimal getProdutos(){return produtos;} public void setProdutos(BigDecimal v){produtos=v;} public BigDecimal getServicos(){return servicos;} public void setServicos(BigDecimal v){servicos=v;} public BigDecimal getTotal(){return total;} public void setTotal(BigDecimal v){total=v;} public StatusCobranca getStatus(){return status;} public void setStatus(StatusCobranca v){status=v;} public LocalDate getDataPagamento(){return dataPagamento;} public void setDataPagamento(LocalDate v){dataPagamento=v;} public BigDecimal getValorPago(){return valorPago;} public void setValorPago(BigDecimal v){valorPago=v;}
}
